"""create tables

Revision ID: 50202d9c2b6d
Revises: 
Create Date: 2025-07-13 21:14:59.104802

"""
import datetime
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from src.common.functions import date_utc_now

# revision identifiers, used by Alembic.
revision: str = '50202d9c2b6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), default=date_utc_now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), default=date_utc_now(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), default=date_utc_now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), default=date_utc_now(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['public.clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_contracts_active', 'contracts', ['active'], unique=False, schema='public')
    op.create_table('energy_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=True),
    sa.Column('reading_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), default=date_utc_now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), default=date_utc_now(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['public.contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_energy_readings_reading_date', 'energy_readings', ['reading_date'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_energy_readings_reading_date', table_name='energy_readings', schema='public')
    op.drop_table('energy_readings', schema='public')
    op.drop_index('idx_contracts_active', table_name='contracts', schema='public')
    op.drop_table('contracts', schema='public')
    op.drop_table('clients', schema='public')
    # ### end Alembic commands ###
